<a href="https://colab.research.google.com/github/yuvrajsinghchauhan01/Machine-Learning101/blob/main/Handling_imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Imbalanced Dataset:
A dataset with an unequal class distribution

In [1]:
# Import libraries

import numpy as np
import pandas as pd

In [2]:
# Load the dataset

credit = pd.read_csv('/content/credit_data.csv')

# first 5 rows

credit.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [3]:
# Shape
credit.shape

(13954, 31)

In [5]:
# distribution of the two classes

credit['Class'].value_counts()

0.0    13897
1.0       56
Name: Class, dtype: int64

This is highly Imbalanced Dataset

0 --- Legit Transaction

1 --- Fraudulent Transaction

In [6]:
legit = credit[credit['Class']==0]
fraud = credit[credit['Class']==1]

In [9]:
legit.shape, fraud.shape

((13897, 31), (56, 31))

In [10]:
# under sampling :- Build a sample dataset containing similar distribution of legit & Fraudulent Transactions

legit_sample = legit.sample(n=70)

In [11]:
legit_sample.shape

(70, 31)

In [12]:
# Concatenate the two data frames
new_dataset = pd.concat([legit_sample, fraud],axis=0)

In [13]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
2021,1562,-0.755694,0.890059,2.297006,0.669007,-0.578496,-0.047670,0.111612,0.048000,0.481642,...,0.065501,0.227281,-0.139697,0.373683,-0.078819,-0.488131,-0.280432,0.076675,9.99,0.0
1164,909,1.187159,-0.934721,-1.379231,-2.272409,1.501795,3.182007,-0.669757,0.786223,1.622727,...,-0.093182,-0.267485,-0.228083,1.083156,0.811431,0.064359,0.004318,0.018598,89.46,0.0
5477,5510,0.953018,0.463259,0.817344,2.351779,0.722928,1.869807,-0.401339,0.562374,0.266740,...,-0.226284,-0.373060,0.268726,-1.137622,-0.119728,-0.193378,0.033836,-0.002159,6.03,0.0
5594,5756,-1.069526,-0.149317,1.679008,-2.419008,0.789008,-0.217896,1.113164,-0.610826,3.102446,...,-0.379733,-0.289215,-0.161039,-0.416205,-0.136385,-1.291803,-0.818651,-0.380878,45.01,0.0
4045,3697,-0.618351,0.965347,1.724017,0.031427,0.658474,0.999573,0.286460,0.428590,0.841700,...,-0.237052,-0.220569,0.156094,-0.715025,-0.573932,0.140805,0.310909,0.103207,2.49,0.0

In [14]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
11880,20451,-15.819179,8.775997,-22.804686,11.864868,-9.092361,-2.386893,-16.560368,0.948349,-6.310658,...,-2.350634,1.036362,1.136051,-1.043414,-0.108923,0.657437,2.136424,-1.411945,1.0,1.0
12070,20931,-16.367923,9.223692,-23.270631,11.844777,-9.462037,-2.450444,-16.925152,1.384208,-6.287736,...,-2.343674,1.004602,1.188212,-1.047184,-0.035573,0.664900,2.122796,-1.416741,1.0,1.0
12108,21046,-16.917468,9.669900,-23.736443,11.824990,-9.830548,-2.514829,-17.290657,1.820408,-6.264903,...,-2.336111,0.972755,1.241866,-1.051086,0.038009,0.672317,2.108471,-1.421243,1.0,1.0
12261,21419,-17.467710,10.114816,-24.202142,11.805469,-10.198046,-2.579938,-17.656788,2.256902,-6.242149,...,-2.328024,0.940830,1.296817,-1.055104,0.111792,0.679695,2.093541,-1.425491,1.0,1.0
12369,21662,-18.018561,10.558600,-24.667741,11.786180,-10.564657,-2.645681,-18.023468,2.693655,-6.219464,...,-2.319479,0.908839,1.352904,-1.059222,0.185751,0.687037,2.078081,-1.429517,1.0,1.0

In [15]:
new_dataset.shape

(126, 31)

In [16]:
new_dataset['Class'].value_counts()

0.0    70
1.0    56
Name: Class, dtype: int64